export const environment = {
  production: false,
  // authUrl: 'https://nhc-educational-system.runasp.net/api/Auth/',
  // userUrl: 'https://nhc-educational-system.runasp.net/api/Users',
  // groupUrl: 'https://nhc-educational-system.runasp.net/api/Groups',
  // attendanceUrl: 'https://nhc-educational-system.runasp.net/api/Attendances',
  // examUrl: 'https://nhc-educational-system.runasp.net/api/Exams',
  // messageUrl: 'https://nhc-educational-system.runasp.net/api/messages',
  // expenseUrl: 'https://nhc-educational-system.runasp.net/api/expenses',
  // videoUrl: 'https://nhc-educational-system.runasp.net/api/videos',
  // subjectUrl: 'https://nhc-educational-system.runasp.net/api/subjects',

  authUrl: 'https://localhost:7273/api/Auth/',
  userUrl: 'https://localhost:7273/api/Users',
  groupUrl: 'https://localhost:7273/api/Groups',
  attendanceUrl: 'https://localhost:7273/api/Attendances',
  examUrl: 'https://localhost:7273/api/Exams',
  messageUrl: 'https://localhost:7273/api/messages',
  expenseUrl: 'https://localhost:7273/api/expenses',
  videoUrl: 'https://localhost:7273/api/videos',
  subjectUrl: 'https://localhost:7273/api/subjects',
  baseUrl: 'https://localhost:7273',
};
